apiVersion: v1
kind: Service
metadata:
  name: mattermost-chatgpt-bot
  namespace: default
spec:
  selector:
    app: mattermost-chatgpt-bot
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP